### PR TITLE
☠  removed dead links and tidied up

### PR DESCRIPTION
**Pull request by Kingston802**
Removed a lot of dead links for AliExpress and commented out unfilled items. Great resource, just needs some more items

### CODE REVIEW

**Comment by 0xjmux** [comment]
Thanks for the pull request!
Usually when updating this repo we try to replace dead links with active ones, if new listings are available. (Like you said, we don't want to take anything out if we don't have to). 

For the links that were removed, would you be willing to try and find replacement items that match the item description?

**Comment by Kingston802** [comment]
@PwnKitteh I added links for the items I could find. Hope that's good now!

**Comment by Kingston802** [comment]
@P

**Comment by 0xjmux** [comment]
Sorry, it's been a chaotic few days and I just got back to this. 

Everything looks good, thanks for the PR and cleaning it up!

**Pull request merged**
